# Generated by Django 4.2.7 on 2023-11-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_city2"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city3",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city4",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city5",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
